export const Data = [
  {
    title: `Sparkle Trailer — "Monodrama" | Honkai: Star Rail`,
    channel: "崩壊：スターレイル",
    url: "https://videogames.si.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MjA0NjYzNzU1MjgyMzI2ODU5/honkai-star-rail-sparkle-trailer-1.png",
    icon: "https://yt3.ggpht.com/MM9AqJ80--wfprw0_5XJrCd1kNewY2jzqMTgk0vPlWbU1_dVQy-U6N45ReLjRCo4PQOJW1rn=s68-c-k-c0x00ffffff-no-rj",
    views: "1.5M views",
    age: "7 days ago",
    time: "10:00",
  },
  {
    title: `Sparkle Trailer — "Monodrama" | Honkai: Star Rail`,
    channel: "崩壊：スターレイル",
    url: "https://videogames.si.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MjA0NjYzNzU1MjgyMzI2ODU5/honkai-star-rail-sparkle-trailer-1.png",
    icon: "https://yt3.ggpht.com/MM9AqJ80--wfprw0_5XJrCd1kNewY2jzqMTgk0vPlWbU1_dVQy-U6N45ReLjRCo4PQOJW1rn=s68-c-k-c0x00ffffff-no-rj",
    views: "1.5M views",
    age: "7 days ago",
    time: "10:00",
  },
  {
    title: `Sparkle Trailer — "Monodrama" | Honkai: Star Rail`,
    channel: "崩壊：スターレイル",
    url: "https://videogames.si.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MjA0NjYzNzU1MjgyMzI2ODU5/honkai-star-rail-sparkle-trailer-1.png",
    icon: "https://yt3.ggpht.com/MM9AqJ80--wfprw0_5XJrCd1kNewY2jzqMTgk0vPlWbU1_dVQy-U6N45ReLjRCo4PQOJW1rn=s68-c-k-c0x00ffffff-no-rj",
    views: "1.5M views",
    age: "7 days ago",
    time: "10:00",
  },
  {
    title: `Sparkle Trailer — "Monodrama" | Honkai: Star Rail`,
    channel: "崩壊：スターレイル",
    url: "https://videogames.si.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MjA0NjYzNzU1MjgyMzI2ODU5/honkai-star-rail-sparkle-trailer-1.png",
    icon: "https://yt3.ggpht.com/MM9AqJ80--wfprw0_5XJrCd1kNewY2jzqMTgk0vPlWbU1_dVQy-U6N45ReLjRCo4PQOJW1rn=s68-c-k-c0x00ffffff-no-rj",
    views: "1.5M views",
    age: "7 days ago",
    time: "10:00",
  },
  {
    title: `Sparkle Trailer — "Monodrama" | Honkai: Star Rail`,
    channel: "崩壊：スターレイル",
    url: "https://videogames.si.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MjA0NjYzNzU1MjgyMzI2ODU5/honkai-star-rail-sparkle-trailer-1.png",
    icon: "https://yt3.ggpht.com/MM9AqJ80--wfprw0_5XJrCd1kNewY2jzqMTgk0vPlWbU1_dVQy-U6N45ReLjRCo4PQOJW1rn=s68-c-k-c0x00ffffff-no-rj",
    views: "1.5M views",
    age: "7 days ago",
    time: "10:00",
  },
  {
    title: `Sparkle Trailer — "Monodrama" | Honkai: Star Rail`,
    channel: "崩壊：スターレイル",
    url: "https://videogames.si.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MjA0NjYzNzU1MjgyMzI2ODU5/honkai-star-rail-sparkle-trailer-1.png",
    icon: "https://yt3.ggpht.com/MM9AqJ80--wfprw0_5XJrCd1kNewY2jzqMTgk0vPlWbU1_dVQy-U6N45ReLjRCo4PQOJW1rn=s68-c-k-c0x00ffffff-no-rj",
    views: "1.5M views",
    age: "7 days ago",
    time: "10:00",
  },
  {
    title: `Sparkle Trailer — "Monodrama" | Honkai: Star Rail`,
    channel: "崩壊：スターレイル",
    url: "https://videogames.si.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MjA0NjYzNzU1MjgyMzI2ODU5/honkai-star-rail-sparkle-trailer-1.png",
    icon: "https://yt3.ggpht.com/MM9AqJ80--wfprw0_5XJrCd1kNewY2jzqMTgk0vPlWbU1_dVQy-U6N45ReLjRCo4PQOJW1rn=s68-c-k-c0x00ffffff-no-rj",
    views: "1.5M views",
    age: "7 days ago",
    time: "10:00",
  },
  {
    title: `Sparkle Trailer — "Monodrama" | Honkai: Star Rail`,
    channel: "崩壊：スターレイル",
    url: "https://videogames.si.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MjA0NjYzNzU1MjgyMzI2ODU5/honkai-star-rail-sparkle-trailer-1.png",
    icon: "https://yt3.ggpht.com/MM9AqJ80--wfprw0_5XJrCd1kNewY2jzqMTgk0vPlWbU1_dVQy-U6N45ReLjRCo4PQOJW1rn=s68-c-k-c0x00ffffff-no-rj",
    views: "1.5M views",
    age: "7 days ago",
    time: "10:00",
  },
  {
    title: `Sparkle Trailer — "Monodrama" | Honkai: Star Rail`,
    channel: "崩壊：スターレイル",
    url: "https://videogames.si.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MjA0NjYzNzU1MjgyMzI2ODU5/honkai-star-rail-sparkle-trailer-1.png",
    icon: "https://yt3.ggpht.com/MM9AqJ80--wfprw0_5XJrCd1kNewY2jzqMTgk0vPlWbU1_dVQy-U6N45ReLjRCo4PQOJW1rn=s68-c-k-c0x00ffffff-no-rj",
    views: "1.5M views",
    age: "7 days ago",
    time: "10:00",
  },
  {
    title: `Sparkle Trailer — "Monodrama" | Honkai: Star Rail`,
    channel: "崩壊：スターレイル",
    url: "https://videogames.si.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MjA0NjYzNzU1MjgyMzI2ODU5/honkai-star-rail-sparkle-trailer-1.png",
    icon: "https://yt3.ggpht.com/MM9AqJ80--wfprw0_5XJrCd1kNewY2jzqMTgk0vPlWbU1_dVQy-U6N45ReLjRCo4PQOJW1rn=s68-c-k-c0x00ffffff-no-rj",
    views: "1.5M views",
    age: "7 days ago",
    time: "10:00",
  },
];
